# Generated by Django 3.1.2 on 2022-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0010_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalDonationCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
