# Generated by Django 3.1.2 on 2022-04-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0009_user_apportionment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
