# Generated by Django 3.1.2 on 2022-03-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blood', '0008_user_apportionment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_Apportionment',
        ),
    ]
