# Generated by Django 3.1.2 on 2022-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0013_auto_20220521_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latestCity',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='latestHospital',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
